### ISSUE TITLE
Deal with Infinity in NonceAgg by Outputting Point at Infinity

### ISSUE THREAD

**Issue by jonasnick** [jonasnick/bips#20]
Our current approach of setting the nonce to `G` has [several problems](https://github.com/jonasnick/bips/pull/11#discussion_r879549130).

**Comment by jonasnick** [comment]
If NonceAgg can output the point at infinity it is also better suited for nested MuSig.

**Comment by LLFourn** [comment]
FWIW in our rust implementation we just return a `Option` when this happens. in `secp256kfun` we don't allow serialization of infinity but I'd be happy to add it and have considered adding it several times myself.

**Comment by real-or-random** [comment]
@LLFourn If you have experience implementing this, do you have an opinion for the discussion at the bottom of #21?

**Comment by LLFourn** [comment]
Hmmm I see the problem is deeper than I thought since BIP340 will not allow infinity so it would be odd to add it here.

My current opinion is that implementations should notify the caller and make them handle it. In many cases aborting will be the right decision. For when you do want to figure out who it was, your suggestion is good: set the agg nonce to `G` just before signing and carry on. I don't think implementations should do this magically behind the scenes though. They should provide `dummy_session` function that is called by the application to opt into this mechanism.

Using a successful aggregated sig against infinity to extract the secret key is a fun idea though!

**Comment by real-or-random** [comment]
> My current opinion is that implementations should notify the caller and make them handle it. In many cases aborting will be the right decision. For when you do want to figure out who it was, your suggestion is good: set the agg nonce to `G` just before signing and carry on. I don't think implementations should do this magically behind the scenes though. They should provide `dummy_session` function that is called by the application to opt into this mechanism.


Hm, I'm not sure if this makes the API unnecessarily complex and pushes down decisions as well as error handling to the user (who may be confused by the choices).

In a correct implementation, you'll see an infinity agg nonce only when it's forced by the attacker. I agree that if that really happens, it may make sense to let the caller know. However, making logic dependent on this will create an error handling/control flow path which is never reached in functional tests but is easy to trigger for the attacker.

In contrast, if we always continue (no matter if we set the final nonce to G or not), there's not much incentive for the attacker to force the nonce to be infinity. There are much easier ways to disrupt the protocol, and they do the same harm.

Of course a buggy implementation could lead to the aggnonce being set to infinity. I think the following bug is plausible:
For some reason, an empty set of nonces is aggregated, which then falls potentially will fall back to infinity as an initial value of an accumulator variable. I believe this is a plausible bug [1] but I don't see how that would be bad or even catastrophic. Yes, signing will fail but apart from this, nothing bad happens. And I believe the same would conclusion will apply for essentially every other bug that would yield an infinity nonce.

(There's also the case that all signers set both their secret nonces to 0. That is another plausible and very bad bug. But this should better be rejected earlier in the signing code, and indeed the signer should abort earlier the because it can't serialize the nonce pair. We can also add another explicit check that reject any secret zero nonce already when reading it from the RNG.)

So in the end, I feel we should not make the API more complicated here, and my favorite approach is still the one I suggested in #21, i.e., setting to `G` just before signing. I can imagine it makes sense to somehow tell the caller that the nonce is infinity, e.g., for debugging or to write a warning to a log file, but again this gives the caller the opportunity to change control flow so I'm not sure it's a good idea.

[1] We may want to add explicit checks in the pseudocode of KeyAgg and NonceAgg that reject empty inputs. At the moment this is somewhat implicit in the notation of the parameters and probably easy to miss when translating the pseudocode to real code. edit: Ok, apparently we made that mistake in our python code...
