### ISSUE TITLE
secnonce/pubnonce naming

### ISSUE THREAD

**Issue by arik-so** [jonasnick/bips#45]
This is more a question than a recommendation, but considering that secnonce and pubnonce are technically concatenations of two nonces, which later have to be split up for a LC calculation, wouldn't pluralizing the names to `secnonces` and `pubnonces` make it a bit more intuitive to readers and implementers?

**Comment by jonasnick** [comment]
That secnonce and pubnonce "are technically concatenations of two nonces" is a technical detail that is irrelevant for users of MuSig2 interfaces. For them these are just a 66 or 64 byte arrays. Therefore, using the plural introduces unnecessary confusion in my opinion.

**Comment by real-or-random** [comment]
> Therefore, using the plural introduces unnecessary confusion in my opinion.

I agree but maybe it's still useful to add a remark or a footnote for readers familiar with the underlying paper. I could understand that the for them, the BIP is slightly confusing because we deviate from the terminology in the papers.

Another approach would be to use a different word altogether, e.g., "preparation message". But this has other drawbacks. (Everyone calls it nonce already...)

**Comment by arik-so** [comment]
I don't really have a strong opinion, but I'm actually coming from exactly the situation Tim described: having read the paper, I found myself double- and triple-checking that I wasn't missing some significant change or a separate location where the other nonce would later came from. 

The plural is also just ever so slightly more precise, and it also implies that there is some sort of underlying serialization that has already happened, so the secret "nonce" may not naïvely be converted to the public one – though that should be fairly obvious simply from its byte count.
