### ISSUE TITLE
KeySort test vectors

### ISSUE THREAD

**Issue by arik-so** [jonasnick/bips#58]
I think it would be helpful for those applications that do not have built-in canonical key ordering to have reference test vectors for the lexicographic key sorting. My current operating assumption is that it's based on the 33-byte-serialization.

**Comment by real-or-random** [comment]
> My current operating assumption is that it's based on the 33-byte-serialization.

I hoped the pseudocode is be pretty clear here:
https://github.com/jonasnick/bips/blob/musig2/bip-musig2.mediawiki#key-sorting

It says public keys are 32-byte arrays.


But oh I think we missed this in #37. So 32 bytes made sense before #37 but it doesn't make sense anymore now because #37 changed the input of key aggregation from 32 bytes to 33 bytes...  

Yeah, we may want to add a simple test vector that catches this.

**Comment by real-or-random** [comment]
@arik-so Does #61 resolve your question/issue?

**Comment by arik-so** [comment]
Yes, thank you very much. Most disambiguating :)
