### ISSUE TITLE
Parity handling in partial signature generation

### ISSUE THREAD

**Issue by arik-so** [jonasnick/bips#59]
It looks like when generating partial signatures, we're currently handling parity for R and Q. Is it a necessary step if 32-byte-pubkeys should only be produced at the PartialSigAgg step? I apologize if I am missing or misunderstanding something obvious.

**Comment by jonasnick** [comment]
I'm not sure if I understand your question. Are you suggesting to generate the aggregate key only at the `PartialSigAgg` step? Besides the practical downsides (can't compute a public key without going through the process of signing), this can't work because the aggregate public key is required when signing as it's input of the challenge hash.

**Comment by arik-so** [comment]
I was suggesting to chop off the parity bit off the pubkey in the PartialSigAgg, but you're right, of course – its use as an input for each partial signature prevents that. Never mind!
