### ISSUE TITLE
Aggregate nonce vs. R nonce naming

### ISSUE THREAD

**Issue by arik-so** [jonasnick/bips#69]
I believe there's a little ambiguity with the naming of nonces. In particular, there is the aggregate nonce, which currently seems to be `R_1 || R_2`. But then there's also R = `R_1 + b * R_2`, which is the ultimate, final aggregate nonce. And then, for partial signing, there's also the linear combination nonce of `k_1 + b * k_2`, though here, of course, it only applies to one individual's secret nonces, and not the sum of all participants'.

I believe it would be really helpful to have some disambiguation. In the [Simple Taproot PR](https://github.com/lightning/bolts/pull/995), Laolu uses the term "combined nonce."

After some very superficial thinking, I do find that these terms make sense to me, personally, though I feel like there are much pithier names out there, waiting to be found:

Combined nonce: `R_1 + b * R_2`, because it's a linear combination. Belonging to one single participant. I don't believe it's actually ever used anywhere in the algorithm, but when talking about it, having a term for it sure would help.

Aggregate nonces: `R_1 || R_2`. The plural might help a bit, for what it's worth, though I believe that's a separate discussion and I don't wish to reopen that can of worms.

Combined aggregate nonce (final?): `R_1 + b * R_2`, where `R_1` and `R_2` are the sums of the values of all participants' nonces.

**Comment by jonasnick** [comment]
> Combined nonce

We call this "effective nonce" in the paper. In the BIP text we apparently don't need to refer to it. The specification and reference  refers to it as `Re` where `e` stands for effective. "Combined" seems like a fair alternative.

> Combined aggregate nonce (final?)

We call this "final nonce" in the "Dealing with Infinity in Nonce Aggregation" section which conveys what it is quite well imo.

Agree that it would be confusing if everyone uses different names for these things. Since we don't mention the term "effective nonce" in the BIP, should we add a glossary?

**Comment by arik-so** [comment]
I think a glossary would be incredibly helpful.

**Comment by arik-so** [comment]
I think perhaps a letter abbreviation for the aggregate nonce serialization might also be useful, what do you think?

**Comment by jonasnick** [comment]
@real-or-random made a good point in private saying that implementations that use the MuSig2 spec should generally not have to refer to the effective nonce. We looked at the BOLT you referred to and [here](https://github.com/lightning/bolts/pull/995/files#r968990097) it seems like they are really referring to the final nonce and not the effective nonce. It wouldn't make sense to send the effective nonce to the, because the other party can't do anything useful with it.

> I think perhaps a letter abbreviation for the aggregate nonce serialization might also be useful, what do you think?

Do you mean having a single letter for what we call `aggnonce`?

**Comment by arik-so** [comment]
Hi Jonas, just to clarify, does that mean that the effective nonce is `R_1 + b * R_2` for one individual participant, and the final nonce is the same, but for the aggnonce? I think this is actually precisely why a glossary would be incredibly helpful, even if it refers to some things that are never technically sent across the wire, but only used as intermediate variable values during method execution.

>  you mean having a single letter for what we call `aggnonce`

Yes, I do personally believe that would be helpful, but I don't really have a strong opinion one way or another.

**Comment by real-or-random** [comment]
> just to clarify, does that mean that the effective nonce is `R_1 + b * R_2` for one individual participant

Yes, we call this effective nonce only when it refers to the nonce (already linear-combined into a single group element) of one individual signer. The  "effective nonce" (at least the public version) is only necessary when doing partial verification, and it's internal to that algorithm. 

By the way in LN, you wouldn't need to do partial verification at all. You could do it to check if the other party signed correctly, yes. But you could instead compute the final Schnorr schnorr signature and see if it verifies. If it doesn't verify, you immediately know it's the other party's fault because it's just 2-of-2.
